<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
	<style>
	* {
		margin: 0 auto;
		padding: 0;
	}

	#wrapper {
		width: 600px;
		background-color: pink;
		text-align: center;
		padding: 10px 20px 20px 20px;
	}

	input {
		margin-right: 10px;
		margin-left: 10px;
	}

	form {
		display: none;
		margin: 20px 0px 10px 0px;
	}
	
	h3 {
		padding: 20px 0px 10px 0px;
	}

	#actualShape {
		width: 99%;
		height: 540px;
		margin-top: 10px;
		display: flex;
	    justify-content: center;
	    align-items: center;
	    overflow: scroll;
	    background-color: #C0C0C0;
	}

	</style>
</head>
<body>
	<!-- ___________ PHP _____________ -->

	<?php 

		$cS = $_POST["chosenShape"];
		$r = $_POST["radius"];
		$sM = $_POST["sideM"];
		$rH = $_POST["recHeight"];
		$rW = $_POST["recWidth"];
		
		if ($cS === "circle") {
			$d = 2 * $r;
			$cA = 3.14 * $r * $r;
			$cC = 2 * 3.14 * $r;

			$result = "Given Radius: " . $r . "<br>Diameter: " . $d . " ( Radius x 2 )" . "<br>Area: " . $cA . " ( π x Radius x Radius )" . "<br>Circumference: " . $cC . " ( 2 x π x Radius )";

			$shapeMaker = "<div style=\"border-radius:50%; width:{$d}px; height:{$d}px; background-color:#FF8040; border: 2px solid #40BFFF;\"></div>";

		} else if ($cS === "square") {
			$sA = $sM * $sM;
			$sP = 4 * $sM;

			$result = "Given (1)Side Measurement: " . $sM . "<br>Area: " . $sA . " ( Measurement x Measurement )" . "<br>Perimeter: " . $sP . " ( 4 x Measurement )";

			$shapeMaker = "<div style=\"width:{$sM}px; height:{$sM}px; background-color:#FF8040; border: 2px solid #40BFFF;\"></div>";

		} else if ($cS === "rectangle") {
			$rA = $rH * $rW;
			$rP = 4 * $rA;

			$result = "Given Height: " . $rH . "<br>Given Width: " . $rW . "" . "<br>Area: " . $rA . " ( Height x Width )" . "<br>Perimeter: " . $rP . " ( 4 x Area )";

			$shapeMaker = "<div style=\"width:{$rW}px; height:{$rH}px; background-color:#FF8040; border: 2px solid #40BFFF;\"></div>";
		}

		$calculatedResults = $result;
		$shapeProvider = $shapeMaker;

	?>

	<!-- ____________ HTML ___________ -->

	<div id="wrapper">
		
		<h1>YOOBEE CALCULATOR</h1>
		
		<?php include("calculator.php") ?>

		<p>Please choose the shape for which you want to calculate properties:</p>
		
		<input type="hidden" name="shape" value="" checked>
		<input type="radio" name="shape" value="circle" id="circle" onchange="shapeType(this.value)"> 
		<label for="cirlce">Circle</label>
		<input type="radio" name="shape" value="square" id="square" onchange="shapeType(this.value)">
		<label for="square">Square</label> 
		<input type="radio" name="shape" value="rectangle" id="rectangle" onchange="shapeType(this.value)"> 
		<label for="rectangle">Rectangle</label>
		
		<form action="yoobeeCalculator.phtml" method="post" id="circleCalculator">
			<label>Enter Radius: </label>
			<input type="text" name="radius" value="">
			<input type="hidden" name="chosenShape" value="circle">
			<button type="submit">Submit</button>
		</form>	

		<form action="yoobeeCalculator.phtml" method="post" id="squareCalculator">
			<label>Enter (1)Side Measurement: </label>
			<input type="text" name="sideM" value="">
			<input type="hidden" name="chosenShape" value="square">
			<button type="submit">Submit</button>
		</form>	

		<form action="yoobeeCalculator.phtml" method="post" id="rectangleCalculator">
			<label>Enter Height: </label>
			<input type="text" name="recHeight" value="">
			<label>Width: </label>
			<input type="text" name="recWidth" value="">
			<input type="hidden" name="chosenShape" value="rectangle">
			<button type="submit">Submit</button>
		</form>

		<br>

		<div id="results">
			<h3>Properties:</h3>
			<?php echo $calculatedResults ?>
		</div>

		<div id="actualShape">
			<?php echo $shapeProvider; ?>
		</div>
				
	</div>

	<script src="custom.js"></script>
</body>
</html>